### ISSUE TITLE
Responsiveness

### ISSUE THREAD

**Issue by elotroalex** [stylerevolution/stylerevolution.github.io#10]
Evaluate for responsiveness in 3 sizes (smartphone, tablet and laptop), and repair specific breaks. Ex. Footer. Max 5 hours.

**Comment by mnyrop** [comment]
## Running Issue list:
- [ ] Hamburgerize menu @media < 400px 
- [ ] Find a way to stack footer (w/o boostrap 😢)
- [ ] Disallow zoom on scroll when @media height < 500 (easier to scroll past IIIF viewer on phone)

**Comment by elotroalex** [comment]
Hm. I don't know if hamburgerize is the right approach. Let me research
stacking instead.

**Comment by mnyrop** [comment]
Hi @elotroalex, I added simple clearfix/stacking to the header and footer 🚫🍔
Feel free to play around with it in dev tools and let me know if it suffices? 
If not I can reopen issues.

(Changes are live at https://stylerevolution.github.io)
